#!/usr/bin/env bash
#ddev-generated
# Remove the line above if you don't want this file to be overwritten when you run
# ddev add-on get FreelyGive/ddev-drupal-canvas-create
#
# This file comes from https://github.com/FreelyGive/ddev-drupal-canvas-create
#
## Description: Create the Drupal Canvas scaffold.
## Usage: canvas-create

npx @drupal-canvas/create@latest storybook --template=acquia-nebula
rsync -rl --remove-source-files --ignore-missing-args storybook/.agents storybook/.claude ./

# Remove self once finished.
rm /var/www/html/.ddev/commands/web/canvas-create
